name: deligo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_phoenix: ^1.0.0
  equatable: ^2.0.3
  google_maps_flutter: ^2.0.6
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  animation_wrappers: ^3.0.0
  scrollable_positioned_list: ^0.3.8


dependency_overrides:
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: "^0.9.0"
#  flutter_launcher_name: "^0.0.1"
  #  flutter_native_splash: ^2.2.5
  flutter_lints: ^4.0.0

#flutter_native_splash:
#  color: "#ffffff"
#  image: assets/splash.png
#  android: true
#  ios: true

#flutter_icons:
#  android: "ic_launcher"
#  ios: true
#  image_path: "assets/app_icon.png"

flutter_launcher_name:
  name: "Deligo"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/category/
    - assets/banner/
    - assets/header/
    - assets/food/
    - assets/grocery/
    - fonts/

  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Bold.ttf
        - asset: fonts/ProductSans-Regular.ttf

flutter_intl:
  enabled: true
  class_name: AppLocalizations